[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
read = [
    { run = 'zathura "$@"', block = false, for = "unix" },
]
[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/pdf", use = "read" },
    { mime = "application/epub+zip", use = "read" },
]
